# Generated by Django 3.2 on 2021-04-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('DOB', models.DateField()),
                ('tested_date', models.DateField(auto_now_add=True)),
                ('test', models.CharField(choices=[('ANTIGEN', 'ANTIGEN'), ('PCR', 'PCR')], max_length=10)),
                ('status', models.CharField(choices=[('DEAD', 'DEAD'), ('TESTED_POSITIVE', 'POSITIVE'), ('QUARANTINED', 'QUARANTINED')], max_length=17)),
                ('tel_no', models.CharField(max_length=10)),
                ('address', models.TextField()),
            ],
        ),
    ]
