# Generated by Django 3.2 on 2021-04-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ('-tested_date',)},
        ),
        migrations.AlterField(
            model_name='patient',
            name='tested_date',
            field=models.DateField(),
        ),
    ]
